# netlify.toml

[build]
  publish = "build"
  command = "npm run build"
  functions = "functions/"

[dev]
  command = "npm run dev"
  port = 8888
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
